create table customer (ID NUMBER(11) PRIMARY KEY, NAME VARCHAR2(30), BALANCE NUMBER(20,2));

create table transactions (MOBILE_NUMBER NUMBER(11), TRANSACTION_DATE VARCHAR2(11), TRANSACTION_TYPE VARCHAR2(15), TRANSACTION_STATUS VARCHAR2(15), AMOUNT NUMBER(20,2));

